name: tayseer__app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0

  google_sign_in: ^6.1.5


  intl_phone_number_input: ^0.7.3+1
  country_picker: ^2.0.20
  email_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets\images\background.jpg
    - assets\images\w.jpg
    - assets\images\ghbayri.png
    - assets\images\houla.png
    - assets\images\kawneen.png
    - assets\images\kheyam.png
    - assets\images\arabsalim.png
    - assets\images\bleeda.png
    - assets\images\ghazeyi.png
    - assets\images\maysljabal.png
    - assets\images\sohmor.png

  fonts:
    - family: funnel
      fonts:
        - asset: assets\fonts\funnel.ttf
